### ISSUE TITLE
track order messed up on multi cd albums

### ISSUE THREAD

**Issue by maxsubs** [vhaudiquet/BladePlayer#15]
If the album on my library has more than one cd, the order of the tracks isn't right, they go 101, 201, 102, 202, 103, 203... take [this](https://open.spotify.com/album/7cYSaPFZ6t2av8K35qk8ga?si=OuULBhIUSzOBCUetaEABVw) as an example.
I don't know if this can be solved or we should get around it by creating a playlist for these albums. OT: any way to access spotify web or some unofficial client that let's you add/remove albums or create playlists? I just don't want the official player installed only for this. This is an amazing app! thanks!

**Comment by vhaudiquet** [comment]
Mmmh interesting bug i did not know about these "multi-cd" albums !
I'll try to look into it if i have the time...

Thank you for reporting this and for your interest in my app !
