### ISSUE TITLE
Outdated links in Izzy's repository

### ISSUE THREAD

**Issue by yephny** [vhaudiquet/BladePlayer#2]
All of the links in Izzy's repository lead to a non-existent Github profile, Valou3433.

**Comment by vhaudiquet** [comment]
Mmmh...
I was not aware that my app was on Izzy's repository.
I'm not the one who put it there, and i'm not really familiar with that.

NOTE to self : link is https://apt.izzysoft.de/fdroid/index/apk/v.blade

I'll try to look into it

**Comment by yephny** [comment]
Izzy's F-Droid repository is the most common repo after the official F-Droid respository. It is a less restrictive database and it pulls `apk`s directly from developers in comparison to F-Droid building each app themselves.

I recommend keeping the app in the repository, if and until Blade is released on the official F-Droid repo. It's great for discoverability and allows auto/easy app updates for users.
