### ISSUE TITLE
How does Blade work without Premium?

### ISSUE THREAD

**Issue by yephny** [vhaudiquet/BladePlayer#24]
I had a Spotify Premium account when I first set up Blade, but I don't have a premium subscription anymore. How does Blade still play music from Spotify?

**Comment by vhaudiquet** [comment]
You mean that is still plays music now even though your subscription ended ?

If so, it is a bug on Spotify servers i guess, and a major one !

**Comment by vhaudiquet** [comment]
Just out of curiosity, do you have any update on this ? Is Blade still working without your Spotify Premium or was is just a cache thing ?

**Comment by yephny** [comment]
@vhaudiquet I confirm that I can play songs that I've never listened to before with Blade Player. It's been some time my premium subscription ran out.

**Comment by yephny** [comment]
Have you tested it with a non-premium account? If so, there could be a condition that you need premium only for the first time you set up Blade for it work.

**Comment by vhaudiquet** [comment]
Never tested it no, i have spotify premium...

Back-end used is [librespot-java](https://github.com/librespot-org/librespot-java), but they say that it shouldn't work without premium, soooo....

i don't know what is happening

**Comment by TomBonnot** [comment]
I have tried to setup a non premium account (well, I’ve asked a friend of mine to do so, she was using a weird apk of Spotify) and everything works just fine, and she doesn’t have Premium, so I guess it’s a trick, and there is no ads

**Comment by primski** [comment]
Does the Blade still work for you guys with Spotify Free accounts? I get authentication error since latest spotify update ( a week or so ) and can't use it anymore. Tried it with spotify app also installed and logged in and without and makes no difference. thanks.

**Comment by vhaudiquet** [comment]
Did you download the new release (version 2.2.1) ?

This release changed something arround the auth flow, because Spotify changed their own auth flow.
Maybe they changed it to fix non-premium accounts login, or maybe you're just using an older release that just can't connect to Spotify ?

**Comment by primski** [comment]
I've been using it for ages just fine and last week just stopped working. I have not tried the new version yet as it's not yet updated on the Play Store but i'm planning to, just thought i'd ask if it's a common issue. Not sure what i could be doing wrong tho.

Thanks for the help and the awesome app :)

**Comment by vhaudiquet** [comment]
Okay, then it is for sure because you don't have the latest release; it happened to me too, and I have premium.
Yet i could not login on Spotify.

The latest update fixes that, i already updated it on the Play Store but they will take a week or so to verify the release and publish it. If you want it faster, just download the APK from the release section here.

Anyway, if it still works without premium for you, tell me !

**Comment by primski** [comment]
just tried the new version manually and yes, i can login again, so it does work!  am playing a song, no ads for now. nice, thanks a lot! :)
