### ISSUE TITLE
Spotify more user friendly

### ISSUE THREAD

**Issue by siggi1984** [vhaudiquet/BladePlayer#28]
Have recently discovered the player. It works very well even with Spotify very reliable. But the operation with Spotify is very cumbersome. I would like it if the operation with Spotify would be a little nicer and better similar to Spotube would be cool.

Maybe just take a look at Spotube.

https://github.com/KRTirtho/spotube

I hope the app stays around for a long time and becomes more user friendly.

Thank you for all your hard work.

**Comment by vhaudiquet** [comment]
Hi,

I'm not sure I understand what you mean.
Do you mean the Spotify login flow could be more user-friendly ? If so, i totally agree with you, and i'm already thinking about a new way to login more smoothly.

If you mean the interaction between your playlists and albums from Spotify, i'm not sure i see what you mean. I installed Spotube and i've seen that they feature a "home page" with new genres or personalized playlists from Spotify; is that a thing you would want in BladePlayer ?

**Comment by siggi1984** [comment]
The login to Spotify is already fine.

I mean the e.g. search function, the artist page display, interaction between the artists and albums and playlists should be similar to Spotify or Spotube. Personally, I find Spotube or Spotify user friendly and easier to use.
Übersetzt mit DeepL https://www.deepl.com/app/?utm_source=android&utm_medium=app&utm_campaign=share-translation

**Comment by vhaudiquet** [comment]
Okay, i get what you mean. I'm mostly a 'back-end' developer, and i'm not really an expert of User Interfaces (UI) so i try to keep it simple.

I'll try to look into adding options to display stuff differently, more like a grid maybe and with categories to show new stuff, etc..

**Comment by siggi1984** [comment]
Okay great, sounds good. I am curious about the further development of the APP...

**Comment by siggi1984** [comment]
There's nothing going on here.
