### ISSUE TITLE
Categorize local search the same as explore search

### ISSUE THREAD

**Issue by LakkesW** [vhaudiquet/BladePlayer#6]
At the moment you can only search for song titles. However, I often also want to search for artists. Adding this seems to be fairly simple. But thinking a little further, searching for playlists or albums could be needed as well. The search probably should differ depending on the currently selected category in the navigation drawer. Here are my thoughts:

artists -> search for artists
albums -> search for album name and artist
songs -> search for song title and artist
playlists -> search for playlist name

**Comment by vhaudiquet** [comment]
The issue with this is that if you are inside of an album, what do you search for ?

But i found a solution to that, in the "explore mode", search returns a categorized view (first songs, then albums, then artists, ...).
I will do the same for local search, it is already planned  :))

**Comment by LakkesW** [comment]
nice :)
