### ISSUE TITLE
Album Artist tag

### ISSUE THREAD

**Issue by resom78** [vhaudiquet/BladePlayer#9]
Hi,
When playing with the local library it would be nice to have an option to sort the "Artist" by "Album Artist" tag, like many other players do.
Otherwise your player is really nice to use with spotify!

**Comment by vhaudiquet** [comment]
I don't really understand what that means ? Sorting by "album artist" ? You mean grouping together artists that have collaborated on albums ? Or hiding artists that are not "album artists" i.e. that only appears in collaborations albums ?

**Comment by resom78** [comment]
The second option is the right one: when you edit tag in a song you can have a field "artist" and a field "album artist". In the first one you can have different artist name for the same album and the main artist is in the field "album artist".
    Le mardi 22 février 2022, 20:40:09 UTC+1, Valentin HAUDIQUET ***@***.***> a écrit :  
 
 


I don't really understand what that means ? Sorting by "album artist" ? You mean grouping together artists that have collaborated on albums ? Or hiding artists that are not "album artists" i.e. that only appears in collaborations albums ?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Akruidenberg** [comment]
I have the same issue with this. Album Artist is much better.
